language: python
python:
  - "3.5"
cache: pip

before_script:
  - echo TRAVIS_BRANCH=${TRAVIS_BRANCH}
  - echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - echo TRAVIS_TAG=${TRAVIS_TAG}
  - echo MTB_PR=${MTB_PR}
  - echo MTB_MERGE_MASTER=${MTB_MERGE_MASTER}

before_install:
  - sudo apt-get install -y figlet
  - pip install awscli

script:
  # Master branch was pushed or marged by feature branches
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      figlet Master Branch Deploy;

      export ENV=dev;
      echo "[INFO] Master branch was pushed or marged by feature branches";
      echo "[BUILD] Deploy Stack...";

      aws cloudformation deploy \
          --template-file=./cloudformation/template.yaml \
          --stack-name ${ENV} \
          --parameter-overrides Environment=${ENV} \
          --region ${AWS_REGION};
    fi

  # Pull Requests was created for feature to master
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      figlet Pull Request Build;

      export ENV=dev;
      echo "[INFO] Pull Request was created";
      echo "[BUILD] Create Stack...";
      DATE=$(date +"%Y%m%d%H%M%S");

      aws cloudformation create-change-set \
          --template-body file://cloudformation/template.yaml \
          --change-set-name "change-set-${DATE}" \
          --stack-name ${ENV} \
          --parameters ParameterKey=Environment,ParameterValue=${ENV} \
          --region ${AWS_REGION};
    fi

  # Feature branch was pushed
  - |
    if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      figlet Only Pushed;
      figlet Nothing to do;
      echo "[INFO] Feature branch was pushed";
      echo "[INFO] Nothing to do anything";
    fi
