language: python
python:
  - "3.5"
cache: pip

before_install:
  - pip install awscli

script:
  - aws cloudformation deploy
      --template-file=./cloudformation/template.yaml
      --stack-name dev
      --parameter-overrides Environment=dev
      --region us-east-1
