- hosts: all
  become: yes
  tasks:
   - name: install Apache
     yum: pkg={{item}} state=installed
     with_items:
      - httpd
   - name: enable httpd service
     service: name=httpd enabled=yes
