AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce
Resources:
  StackDelete:
    Properties:
      CodeUri: s3://api-backend-test-bucket/72c496a49bd075f216d1fd822d251e1b
      Events:
        Day:
          Properties:
            Schedule: cron(0 22 * * ? *)
          Type: Schedule
      FunctionName: stack_delete_bot
      Handler: stack_delete_bot.lambda_handler
      Role:
        Fn::GetAtt:
        - StackDeleteNoticeIAMRole
        - Arn
      Runtime: python3.6
      Timeout: 180
    Type: AWS::Serverless::Function
  StackDeleteNoticeIAMRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: cloudformation:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: stack-delete-notice-policy
      RoleName: stack-delete-notice-role
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
